### ISSUE TITLE
bump meta-sunxi

### ISSUE THREAD

**Issue by ebutera** [Angstrom-distribution/angstrom-manifest#15]
i just fixed a build problem in meta-sunxi so it should be bumped to latest master (8a9c1d688c80f21c28836e7fa3e8f945ca84927b) or, better, use the just-created fido branch

**Comment by kraj** [comment]
Can we still use master for master and fido for 2015.12 release ?

**Comment by ebutera** [comment]
I'd use:
fido for 2015.06
master for master
master for 2015.12 (to be later switched to whatever release name will be used)

**Comment by kraj** [comment]
OK would you mind sending a patch too ?

**Comment by ebutera** [comment]
i've sent you the patch for 2015.06 branch by email, first time fiddling with repo xml so if it's correct i'll send another one for master

**Comment by ebutera** [comment]
made a pull request, no need to do it for master since as i understand there is no revision pinned

**Comment by kraj** [comment]
> On Aug 22, 2015, at 8:33 AM, Enrico Butera notifications@github.com wrote:
> 
> done, no need to do it for master since as i understand there is no revision pinned

thanks merged. Yes master tracks tip always
