### ISSUE TITLE
revision of the kraj/meta-altera

### ISSUE THREAD

**Issue by ilya1725** [Angstrom-distribution/angstrom-manifest#24]
The revision of `kraj/meta-altera` project in the `angstrom-v2015.12-yocto2.0` branch specified in the manifest file is from July 6th last year.
Is there any reason not to update it? I'm asking because it is missing the component I would like to use.

**Comment by koenkooi** [comment]
I have no objection to updating it, I suspect it was an oversight.

**Comment by kraj** [comment]
updated to latest in angstrom-v2017.06-yocto2.3
