### ISSUE TITLE
image_types_uboot missing?

### ISSUE THREAD

**Issue by feddischson** [Angstrom-distribution/angstrom-manifest#31]
Hi,

I am new to bitbake as well as to angstrom, but I tried the following ... 
```
mkdir angstrom && cd angstrom
repo init -u git://github.com/Angstrom-distribution/angstrom-manifest
repo sync
MACHINE=cyclone5 . ./setup-environment
bitbake world
```
... and ended up with
```
ERROR: ParseError at /home/christian/Development/fpga/DE0/angstrom/layers/meta-linaro/meta-linaro/recipes-linaro/images/linaro-image-minimal-initramfs.bb:39: Could not inherit file classes/image_types_uboot.bbclass
```

Here is the config output:
```
Your build environemnt has been configured with:

    MACHINE=cyclone5
    SDKMACHINE=x86_64
    DISTRO=angstrom

You can now run 'bitbake <target>'

Some of common targets are:
    console-image
    systemd-gnome-image
    xfce-nm-image
    development-xfce-image
    development-gnome-image

```

Also `bitbake console-image` gives me the same error.

**Comment by kraj** [comment]
Hmm this class was merged into image bbclass via

[OE-Core Commit](http://cgit.openembedded.org/openembedded-core/commit/?id=65f27122950a35a67ce39ae4cfe93d0dca6b0dab)

please remove inheriting it from

meta-linaro/recipes-linaro/images/linaro-image-minimal-initramfs.bb

this should be submitted to meta-linaro as well.

**Comment by feddischson** [comment]
Seems to work (I submitted this also to OpenEmbedded@lists.linaro.org), but further problems can be observed.

Do you want me to create individual issues?

**Comment by kraj** [comment]
what more issues do you see ? if they are related to this then you can continue otherwise open a new ticket
