### ISSUE TITLE
sysmocom/meta-telephony

### ISSUE THREAD

**Issue by feddischson** [Angstrom-distribution/angstrom-manifest#32]
It seems sysmocom/meta-telephony got empty.

https://github.com/sysmocom/meta-telephony

**Comment by koenkooi** [comment]
Thanks for the heads up, I deleted it from all the branches, can you check if it is fixed?

**Comment by feddischson** [comment]
It seems to work.

For what was sysmocom/meta-telephony use for?

**Comment by koenkooi** [comment]
for creating GSM basestations and surrounding technology.
