### ISSUE TITLE
bitbake failed when building de10-nano-image

### ISSUE THREAD

**Issue by jiahaow** [Angstrom-distribution/angstrom-manifest#33]
Sorry,  python version 3.4.0 or later is required by this version bitbake. However, Clone the manifest or Fetch repositories need only python 2.

**Comment by koenkooi** [comment]
Yes, bitbake used python3 while repo uses python2. This is working as intended.

**Comment by jiahaow** [comment]
bitbake failed because of ./tools/python ->/usr/bin/python2.7 when building de10-nano-image.

bitbake failed again after I link /tools/python to /usr/bin/python3.4. 

How to setup python to bitbake de10-nano-console after getting de10-nano repo?

**Comment by jiahaow** [comment]
Thanks!

bitbake failed because of ./tools/python ->/usr/bin/python2.7 when building
de10-nano-image.

bitbake still failed after I link/usr/bin/python3.4 to  ./tools/python or
/usr/bin/python.

How to setup python to bitbake de10-nano-image after getting de10-nano repo?

**Comment by jiahaow** [comment]
correct link for python listed below:
ln -s /usr/bin/python2 /usr/bin/python
ln -s /usr/bin/python3.4 /usr/bin/python3

**Comment by kraj** [comment]
OE still wants python to point to python2, so if you are using a distro where default python has moved to python3 then you would have to switch back to use python2 as python. Angstrom cant help with that.

tools/python pointing to /usr/bin/python2.7 or /usr/bin/python2 means same thing. I dont know why
it behave differently for your system.
