### ISSUE TITLE
angstrom-v2017.12-rocko fails

### ISSUE THREAD

**Issue by JanP** [Angstrom-distribution/angstrom-manifest#38]
Hi,

When building the console-image or any other image on the rocko branch, I get the following error:
Error: ParseError at layers/meta-backports/core/recipes-connectivity/iproute2/iproute2_4.17.0.bb:1: Could not include required file iproute2.inc

The mentioned file exists: layers/openembedded-core/meta/recipes-connectivity/iproute2/iproute2.inc
When I check the bblayers.conf file, it has the directory layers/openembedded-core/meta for BBLAYERS.

Any idea on why this seems to go wrong?

Kind regards,

Jan

**Comment by koenkooi** [comment]
This is a bug with meta-backports, but I'll keep it open till it gets resolved upstream, or we lock meta-backports to a rev before the breakage.

```[koen@fedora-vm v2017.12]$ repo grep  iproute2.inc
layers/meta-backports/core/recipes-connectivity/iproute2/iproute2_4.17.0.bb:require iproute2.inc
layers/openembedded-core/meta/recipes-connectivity/iproute2/iproute2_4.11.0.bb:require iproute2.inc
```
So 2 recipes require a file called 'iproute2.inc' to be in the same dir as the recipe, but...
```
[koen@fedora-vm v2017.12]$ find layers/ -name "iproute2.inc"
layers/openembedded-core/meta/recipes-connectivity/iproute2/iproute2.inc
```
There's only one file, leading to...
```
Error: ParseError at layers/meta-backports/core/recipes-connectivity/iproute2/iproute2_4.17.0.bb:1: Could not include required file iproute2.inc
```
The fix:
```
[koen@fedora-vm v2017.12]$ repo diff layers/meta-backports

project layers/meta-backports/
diff --git a/core/recipes-connectivity/iproute2/iproute2_4.17.0.bb b/core/recipes-connectivity/iproute2/iproute2_4.17.0.bb
index 6d77106..dd78573 100644
--- a/core/recipes-connectivity/iproute2/iproute2_4.17.0.bb
+++ b/core/recipes-connectivity/iproute2/iproute2_4.17.0.bb
@@ -1,4 +1,4 @@
-require iproute2.inc
+require recipes-connectivity/iproute2/iproute2.inc
 
 SRC_URI = "${KERNELORG_MIRROR}/linux/utils/net/${BPN}/${BP}.tar.xz \
            file://0001-make-configure-cross-compile-safe.patch \
[koen@fedora-vm v2017.12]$ 
```

**Comment by JanP** [comment]
Thanks for the help, that did the trick.

**Comment by koenkooi** [comment]
Fix applied to upstream: https://git.linaro.org/openembedded/meta-backports.git/log/?h=rocko
