### ISSUE TITLE
Feed server? 

### ISSUE THREAD

**Issue by ClowningAround** [Angstrom-distribution/angstrom-manifest#39]
Hello there, 

I've installed 'The Angstrom Distribution socfpga ttyS0' v2014.12 for my de-10 nano chipset. It works great, but when I've tried to run opkg update unfortunately all I get is: 

'Downloading http://feeds.angstrom-distribution.org/feeds/v2014.12/ipk/...' 
'wget: error getting response: Connection reset by peer' 

I have no idea what this means. I tried to follow the links up in my browser, but it couldn't resolve the hostname. Did you take your feeds.angstrom server down? Is there a new feed server? What even is a feed server? 

Thanks, 
Matt

**Comment by kraj** [comment]
feed server is being moved will be up in few days

**Comment by ClowningAround** [comment]
Thanks for the reply, well I'm stuck until it's up as I can't find a mirror anywhere. Could I tempt you to put it up today for say, $20?

**Comment by kraj** [comment]
They are being transported to different colo and ETA is about 1 week.

**Comment by ghost** [comment]
Hello.
Any updates on the feeds link?
Thanks

**Comment by kraj** [comment]
Our admins have updated that servers have arrived in new colo, they are wiring them up now hopefully a day or two we should be up.

**Comment by ghost** [comment]
Thanks alot sir for your update.
I was struggling on that point why I cant update opkg.
Kindly let me know once its done.

Thanks and have a nice day

**Comment by ghost** [comment]
Hello Kraj.
Is there any update on the feeds links?
Thanks for your help

**Comment by ghost** [comment]
The feed links seems to work now.

Thanks

**Comment by ClowningAround** [comment]
Thanks for putting the feed servers back up! Now I can continue my project :)

**Comment by FPGA-Lord** [comment]
Hello.
The feeds seems to be down again
