### ISSUE TITLE
Angstrom build fails due to repo tool error

### ISSUE THREAD

**Issue by eigendude** [Angstrom-distribution/angstrom-manifest#44]
I noticed yesterday that my distro, which I forked from angstrom, stopped building. Vanilla Angstrom now has the same problem:

```
~/Documents/angstrom-manifest$ repo init -u https://github.com/Angstrom-distribution/angstrom-manifest

Traceback (most recent call last):
  File "/home/garrett/Documents/angstrom-manifest/.repo/repo/main.py", line 555, in <module>
    _Main(sys.argv[1:])
  File "/home/garrett/Documents/angstrom-manifest/.repo/repo/main.py", line 530, in _Main
    result = run()
  File "/home/garrett/Documents/angstrom-manifest/.repo/repo/main.py", line 523, in <lambda>
    run = lambda: repo._Run(name, gopts, argv) or 0
  File "/home/garrett/Documents/angstrom-manifest/.repo/repo/main.py", line 212, in _Run
    result = cmd.Execute(copts, cargs)
  File "/home/garrett/Documents/angstrom-manifest/.repo/repo/subcmds/init.py", line 462, in Execute
    self._LinkManifest(opt.manifest_name)
  File "/home/garrett/Documents/angstrom-manifest/.repo/repo/subcmds/init.py", line 314, in _LinkManifest
    self.manifest.Link(name)
  File "/home/garrett/Documents/angstrom-manifest/.repo/repo/manifest_xml.py", line 181, in Link
    self.Override(name)
  File "/home/garrett/Documents/angstrom-manifest/.repo/repo/manifest_xml.py", line 174, in Override
    self._Load()
  File "/home/garrett/Documents/angstrom-manifest/.repo/repo/manifest_xml.py", line 480, in _Load
    self._ParseManifest(nodes)
  File "/home/garrett/Documents/angstrom-manifest/.repo/repo/manifest_xml.py", line 588, in _ParseManifest
    project = self._ParseProject(node)
  File "/home/garrett/Documents/angstrom-manifest/.repo/repo/manifest_xml.py", line 908, in _ParseProject
    self._ParseCopyFile(project, n)
  File "/home/garrett/Documents/angstrom-manifest/.repo/repo/manifest_xml.py", line 1035, in _ParseCopyFile
    self._ValidateFilePaths('copyfile', src, dest)
  File "/home/garrett/Documents/angstrom-manifest/.repo/repo/manifest_xml.py", line 1026, in _ValidateFilePaths
    '<%s> invalid "src": %s: %s' % (element, src, msg))
error.ManifestInvalidPathError: <copyfile> invalid "src": ../../.repo/manifests/setup-environment: bad component: ..
```

My guess is that the repo tool was updated to enforce the condition listed [here](https://gerrit.googlesource.com/git-repo/+/master/docs/manifest-format.md#Element-copyfile): "Copying from paths outside of the project or to paths outside of the repo client is not allowed."

**Comment by koenkooi** [comment]
Thanks for the heads up, it looks like we'll need to move a few files around :(

**Comment by eigendude** [comment]
I just spoke to an engineer at Toradex and he said he just had to move `setup-environment-internal` to the meta layer (meta-angstrom). I'll give that a try. If it works, would you like a PR here and at meta-angstrom?

**Comment by delrizzo** [comment]
Also experiencing the same issue as of this morning.

**Comment by koenkooi** [comment]
> I just spoke to an engineer at another project and he said he just had to move `setup-environment-internal` to the meta layer (meta-angstrom). I'll give that a try. If it works, would you like a PR here and at meta-angstrom?

Yes please!

**Comment by kraj** [comment]
yes this is a fine fix. Please send a full.

**Comment by eigendude** [comment]
My fork is a little different from Angstrom, I wrapped the Readme instructions into a Makefile inspired by LibreELEC. To fix the build, I removed the `<copyfile>` and added a line in the Makefile to `cp setup-environment` to the build directory.

I tried applying a similar strategy here, but the build instructions in Readme.md confuse me, because it seems that they are out-of-tree instructions (it pulls from github) that are also executed in-tree, or something. I removed the `<copyfile>`, but couldn't figure out how to modify the Readme analogous to my Makefile fix. Sorry, but I'm not sure how to proceed.

Here's the diff I applied to my fork, hope it helps:

```
diff --git a/Makefile b/Makefile
index 103066a..e8b29ed 100644
--- a/Makefile
+++ b/Makefile
@@ -73,7 +73,8 @@ init: $(REPO_MANIFEST_REF) FORCE
 REPO_MANIFEST=build/.repo/project.list
 $(REPO_MANIFEST): init
        cd build; \
-         ./repo sync --force-sync
+         ./repo sync --force-sync; \
+         rm -rf setup-environment; \
+         ln -s ../setup-environment .

 # Sync Repo sources
 .PHONY: sync
diff --git a/default.xml b/default.xml
index 6381e05..e04686a 100644
--- a/default.xml
+++ b/default.xml
@@ -15,9 +15,7 @@
   <project remote="githubssh" name="Aclima/meta-sundstrom-hud" path="layers/meta-sundstrom-hud" revision="refs/tags/v1.11.0-rc1"/>

   <!-- Sundstrom stacks -->
-  <project remote="githubssh" name="Aclima/meta-sundstrom" path="layers/meta-sundstrom" revision="refs/tags/v1.11.0-rc3">
-    <copyfile src="../../.repo/manifests/setup-environment" dest="setup-environment"/>
-  </project>
+  <project remote="githubssh" name="Aclima/meta-sundstrom" path="layers/meta-sundstrom" revision="refs/tags/v1.11.0-rc3"/>
   <project remote="githubssh" name="Aclima/meta-aclima" path="layers/meta-aclima" revision="refs/tags/v1.11.0-rc5"/>

   <!-- BSPs (board support packages) -->
```

**Comment by rodinia-hsandlar** [comment]
I created two pull requests, one for each repo:
https://github.com/Angstrom-distribution/angstrom-manifest/pull/45
https://github.com/Angstrom-distribution/meta-angstrom/pull/38
Please note that these only apply to the v2019.06-warrior branch

In order to test this, I had to adjust the manifest in an additional branch to provide adjusted github pathing. See the `rodinia` branch in the angstrom-manifest repo for further detail.

**Comment by Mark-Garstin** [comment]
I too am having the same problem.  I've tracked it down to changes that have been made to repo as of Feb 3rd.  Unfortunately, Google does not allow anyone to download old versions of the repo tool.  I even tried running an old copy of the tool that I have in an old workspace but repo checks to see if you are using a current version every time it runs and then takes you down if you are not current (grumble).

I just tried about an hour ago (on Feb. 24, 2020) to create and build a fresh workspace but the Angstrom distribution still fails to download using repo.  Am I doing something wrong or has the patches mention above not yet been pushed out to the world?

Cheers,

Mark Garstin

**Comment by eigendude** [comment]
The two patches haven't been merged yet. It's the approach taken by Toradex, and I left some LGTMs, so hopefully it's merged soon

**Comment by koenkooi** [comment]
Sorry for the delay, both patches have been merged now, thanks!

**Comment by LakeBreeze** [comment]
The following command:
repo init -u git://github.com/Angstrom-distribution/angstrom-manifest -b angstrom-v2016.12-yocto2.2
still failed (Mar 26, 2020). Would this require a separate merge?

**Comment by eigendude** [comment]
Yes, all previous branches require a separate merge. The remaining ones are:

- [ ] angstrom-v2015.06-yocto1.8
- [ ] angstrom-v2015.12-yocto2.0
- [ ] angstrom-v2016.06-yocto2.1
- [ ] angstrom-v2016.12-yocto2.2
- [ ] angstrom-v2017.06-yocto2.3
- [ ] angstrom-v2017.12-rocko
- [ ] angstrom-v2018.12-thud
- [x] angstrom-v2019.06-warrior

**Comment by gheorgheorghe** [comment]
> Yes, all previous branches require a separate merge. The remaining ones are:
> 
> * [ ]  angstrom-v2015.06-yocto1.8
> * [ ]  angstrom-v2015.12-yocto2.0
> * [ ]  angstrom-v2016.06-yocto2.1
> * [ ]  angstrom-v2016.12-yocto2.2
> * [ ]  angstrom-v2017.06-yocto2.3
> * [ ]  angstrom-v2017.12-rocko
> * [ ]  angstrom-v2018.12-thud
> * [x]  angstrom-v2019.06-warrior

Hello,
What do you mean by "separate merge"? Are you saying that one must merge an existing angstrom repo with some code that defines and points to a "setup-environment-internal" file in meta-angstrom? 

I am trying to download the Angstrom distribution using repo with the following command:
repo init -u git://github.com/Angstrom-distribution/angstrom-manifest -b angstrom-v2016.12-yocto2.2

Thank you,
-Gheorghe

**Comment by eigendude** [comment]
> What do you mean by "separate merge"?

All branches I listed will need their individual PR matching this one, plus the corresponding PR in meta-angstrom.

**Comment by koenkooi** [comment]
A few branches have been updated in the mean time:

> Yes, all previous branches require a separate merge. The remaining ones are:
> 
> * [ ]  angstrom-v2015.06-yocto1.8
> * [ ]  angstrom-v2015.12-yocto2.0
> * [ ]  angstrom-v2016.06-yocto2.1
> * [ ]  angstrom-v2016.12-yocto2.2
> * [ ]  angstrom-v2017.06-yocto2.3
> * [x]  angstrom-v2017.12-rocko
> * [x]  angstrom-v2018.12-thud
> * [x]  angstrom-v2019.06-warrior

**Comment by gheorgheorghe** [comment]
Thank you! Looking forward to seeing the angstrom-v2016.12-yocto2.2 branch patched.

Best,
- Gheorghe

**Comment by gheorgheorghe** [comment]
Hello all,
Has there been some progress on updating any more branches? 
Can you possibly provide an ETA for when the yocto2.2 branch will be patched? Thank you!
Best,
- Gheorghe

**Comment by gheorgheorghe** [comment]
Hello all,

I am trying to get started on building Linux images for the Intel DE10 Nano board, but this issue with the repo tool has left me stuck on the very first step of the [official image build procedure](https://github.com/intel/meta-de10-nano): "cloning the angstrom manifest".

I saw this alternative image building procedure for "adding the meta-altera layer to vanilla Yocto sources":
https://rocketboards.org/foswiki/view/Documentation/YoctoDoraBuildWithMetaAltera

In this tutorial, they set up Poky environment (without the repo tool), add the BSP layer from [kraj/meta-altera](https://github.com/kraj/meta-altera), and configure it for a Stratix 10 board.

Can I use the same steps to build Yocto Linux images for the DE10 nano? After setting up the Poky environment, I would instead add [intel/meta-de10-nano BSP layer](https://github.com/intel/meta-de10-nano) to the Poky environment, instead of kraj/meta-altera as done in the above tutorial.

Do you think this can work?

**Comment by kutenai** [comment]
I too am at a "work halted" position now, kind of in desperate need to build that yocto2.2 branch.

**Comment by kutenai** [comment]
I applied the changes to the remaining yocto1.8 through yocto2.2 versions.
Pull requests
#47 
#49 
#50 
#51 
#52 

I used my own fork and was able to get this working right away. If someone can merge those, the rest of the community should be good to go.

I did a quick test on them locally, so assuming I didn't mess up, they should work.

**Comment by eigendude** [comment]
Thank you for the PRs!

**Comment by gheorgheorghe** [comment]
Thank you! yocto2.2 branch is working with the repo tool now!

**Comment by AnotherGitAccount** [comment]
- `repo init -u https://github.com/Angstrom-distribution/angstrom-manifest -b angstrom-v2018.12-thud` 
- `repo init -u https://github.com/Angstrom-distribution/angstrom-manifest`

still don't work for me. I get this error : 

`raise ManifestInvalidPathError(
error.ManifestInvalidPathError: <copyfile> invalid "src": ../../.repo/manifests/setup-environment: bad component: .repo
`
