### ISSUE TITLE
altera-opensource/meta-altera  is missing?

### ISSUE THREAD

**Issue by TimScott78** [Angstrom-distribution/angstrom-manifest#54]
Hello,
I'm attempting to follow the guide on RocketBoards to build kernal and rootfs for the CycloneV dev kit.  When this string is entered:  

repo init -u git://github.com/Angstrom-distribution/angstrom-manifest -b angstrom-v2019.06-warrior

followed by: repo sync,

I eventually get this error:

error: Cannot fetch altera-opensource/meta-altera from https://github.com/altera-opensource/meta-altera

Does this mean that meta_altera has been moved?  If so, where would it be and how would I point to it in the process of going through the guide?

Thank you!

Tim

**Comment by dnegvesky** [comment]
I don't know why it was removed from altera-opensource, but you might want to try this one:
https://github.com/kraj/meta-altera

**Comment by TimScott78** [comment]
Thank you for the quick reply!  I'll give it a try.

**Comment by koenkooi** [comment]
> Hello,
> I'm attempting to follow the guide on RocketBoards to build kernal and rootfs for the CycloneV dev kit. When this string is entered:
> 
> repo init -u git://github.com/Angstrom-distribution/angstrom-manifest -b angstrom-v2019.06-warrior
> 
> followed by: repo sync,
> 
> I eventually get this error:
> 
> error: Cannot fetch altera-opensource/meta-altera from https://github.com/altera-opensource/meta-altera

That's very strange, since there's no mention of _https://github.com/altera-opensource/meta-altera_ in the manifest, only of Khem's repo: https://github.com/Angstrom-distribution/angstrom-manifest/blob/aca795d253e16d31e8ffc0b0484e4d92741f05a7/default.xml#L28

And on a clean container I just did:

```
repo init -u git://github.com/Angstrom-distribution/angstrom-manifest -b angstrom-v2019.06-warrior
repo sync
```

Which ended with

```
Resolving deltas: 100% (7213/7213), done.
Fetching projects: 100% (36/36), done.
Checking out projects: 100% (36/36), done.
repo sync has finished successfully.
```

I'm guessing the Rocketboard instructions add some extra steps which break things, so this isn't an angstrom bug.

**Comment by TimScott78** [comment]
Great info and reply. Thank you for trying that and providing your results.
Best,
Tim

Sent from my iPhone

On Dec 11, 2020, at 02:44, Koen Kooi <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello,
I'm attempting to follow the guide on RocketBoards to build kernal and rootfs for the CycloneV dev kit. When this string is entered:

repo init -u git://github.com/Angstrom-distribution/angstrom-manifest -b angstrom-v2019.06-warrior

followed by: repo sync,

I eventually get this error:

error: Cannot fetch altera-opensource/meta-altera from https://github.com/altera-opensource/meta-altera<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Faltera-opensource%2Fmeta-altera&data=04%7C01%7Ctim.scott%40milliken.com%7C0ad87491d69047ab1c4d08d89da89b43%7C326271270bbf472d9e35b0b67edbc59a%7C1%7C0%7C637432694794016862%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=HTJ9AX9wJ%2FMCSCDvDUXltyFM%2BTm84nHrWimT9kLHpvo%3D&reserved=0>

That's very strange, since there's no mention of https://github.com/altera-opensource/meta-altera<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Faltera-opensource%2Fmeta-altera&data=04%7C01%7Ctim.scott%40milliken.com%7C0ad87491d69047ab1c4d08d89da89b43%7C326271270bbf472d9e35b0b67edbc59a%7C1%7C0%7C637432694794016862%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=HTJ9AX9wJ%2FMCSCDvDUXltyFM%2BTm84nHrWimT9kLHpvo%3D&reserved=0> in the manifest, only of Khem's repo: https://github.com/Angstrom-distribution/angstrom-manifest/blob/aca795d253e16d31e8ffc0b0484e4d92741f05a7/default.xml#L28<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAngstrom-distribution%2Fangstrom-manifest%2Fblob%2Faca795d253e16d31e8ffc0b0484e4d92741f05a7%2Fdefault.xml%23L28&data=04%7C01%7Ctim.scott%40milliken.com%7C0ad87491d69047ab1c4d08d89da89b43%7C326271270bbf472d9e35b0b67edbc59a%7C1%7C0%7C637432694794026860%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=N%2BKgcKYCxHTJGyHh2kqL01sf7DEqFMipt%2BOwutK1Ths%3D&reserved=0>

And on a clean container I just did:

repo init -u git://github.com/Angstrom-distribution/angstrom-manifest -b angstrom-v2019.06-warrior
repo sync


Which ended with

Resolving deltas: 100% (7213/7213), done.
Fetching projects: 100% (36/36), done.
Checking out projects: 100% (36/36), done.
repo sync has finished successfully.


I'm guessing the Rocketboard instructions add some extra steps which break things, so this isn't an angstrom bug.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAngstrom-distribution%2Fangstrom-manifest%2Fissues%2F54%23issuecomment-743031853&data=04%7C01%7Ctim.scott%40milliken.com%7C0ad87491d69047ab1c4d08d89da89b43%7C326271270bbf472d9e35b0b67edbc59a%7C1%7C0%7C637432694794036852%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=mCr1i1dI1hZp4h0%2FNyKTBtgEM7lIsjngZXc3Z8%2BS5%2Fk%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FASB6XMIAV6PKNGXWKT2FVWDSUHEWHANCNFSM4UVNDRCA&data=04%7C01%7Ctim.scott%40milliken.com%7C0ad87491d69047ab1c4d08d89da89b43%7C326271270bbf472d9e35b0b67edbc59a%7C1%7C0%7C637432694794036852%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Y61X8IH2Yax8047whdKuOPBJttDm9xEj8ztVIcs6i08%3D&reserved=0>.


________________________________
Confidentiality and Commercial Terms and Conditions Notice:

This message may contain privileged or confidential information and is intended only for the use of the addressee. Please advise immediately if you or your employer do not consent to e-mail for messages of this kind. If you are not the addressee, or person responsible for delivering this message to the person addressed, you may not copy or deliver this to anyone else. If you receive this message by mistake, please notify the sender immediately by return e-mail. All commercial transactions, offers and acceptances are exclusively subject/limited to and conditioned upon our terms posted at our Terms and Conditions<https://www.milliken.com/terms> page. We object to and reject any additional/different terms and conditions unless we expressly agree to them in writing.


Privacy Terms:

Our Data Protection Notices meet the high data protection standards set by the European General Data Protection Regulation (“GDPR”). You have the right to object to the processing of personal data for direct marketing purposes at any time. For more information about our data protection practices and to view a copy of our Data Protection Notices please refer to our Privacy<https://www.milliken.com/Privacy> page.
________________________________
